config/routes.rb
Writup::Application.routes.draw do
  
  root "pages#home"
  match "/help", to: 'pages#help', via: 'get'
  match "/contact", to: 'pages#contact', via: 'get'
  match "/about", to: 'pages#about', via: 'get'
  match "/signup", to: "users#new", via: "get"
  match "/signin", to: "sessions#new", via: 'get'
  match "/signout", to: "sessions#destroy", via: 'delete'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts, only: [:create, :destroy, :show]
  resources :relationships, only: [:create, :destroy]
  

  

end

app/views/layouts/_current_user_header.html.erb
<div class="media">
  <%= link_to gravatar_for(current_user, size: 75, class: "media-object"), current_user, class: "pull-left" %>
  <div class="media-body">
    <h3 class="media-heading"><%= "#{current_user.first_name} #{current_user.surname}" %></h3>
    <p><strong>Email: </strong> <%= current_user.email %> <%= pluralize(current_user.posts.count, "Posts") %></p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. </p>
  </div>
</div>

app/views/layouts/_flash_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<section id="flash_messages">
  <% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <strong><%= key.capitalize %>!</strong> <%= value %>
  </div>
  <% end %>
</section>

app/views/layouts/_navigation.html.erb
<%# Fixed navbar %>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Writup", root_path, class: "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"> <%= link_to "Home", root_path %></li>
        <li> <%= link_to "Profile", current_user %> </li>
        <!--<li> <%= link_to "Posts", "#" %> </li>-->
        <li> <%= link_to "Writers", users_path %> </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to "About", about_path %> </li>
        <li> <%= link_to "Contact", contact_path %> </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= "Account" %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
            <li class="divider"></li>
            <li class="dropdown-header">Settings</li>
            <!--<li> <%= link_to "Account settings", "#" %> </li>-->
            <li> <%= link_to "Profile settings", edit_user_path(current_user) %> </li>
            <!--<li> <%= link_to "Timeline settings", "#" %> </li>-->
          </ul>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%=
#link_to 'About', page_path('about')
%></li>

app/views/layouts/_navigation_not_signed_in.html.erb
<%# Fixed navbar %>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Writup", root_path, class: "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <!--<li class="active"> <%= link_to "Home", root_path %></li>-->
        <!--<li> <%= link_to "Posts", "#" %> </li>-->
        <!--<li> <%= link_to "Writers", users_path %> </li>-->
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to "About", about_path %> </li>
        <li> <%= link_to "Contact", contact_path %> </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">You're not signed in <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li> <%= link_to "Sign In", signin_path %> </li>
            <li> <%= link_to "Sign up", signup_path %> </li>
          </ul>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/_post_form.html.erb
<div class="media">
  <%= link_to gravatar_for(current_user, size: 75, class: "media-object"), current_user, class: "pull-left" %>
  <div class="media-body">
    <%= form_for(@post) do |f| %>
      <%= render "shared/post_create_error_message", object: f.object %>
      <div class="post_input_field">
        <% if @post.errors.include?(:title) %>
          <span class="label label-danger"><% @post.errors.full_messages_for(:title) %></span>
        <% end %>
        <%= f.text_field :title, placeholder: "title of your post", class: "wysihtml5 form-control form-control-margined" %>
        <% if @post.errors.include?(:content) %>
          <span class="label label-danger"><%= @post.errors.full_messages_for(:content) %></span>
        <% end %>
        <%= f.text_area :content, class: "wysihtml5 form-control form-control-margined form-control-heightened", style: "display: block; height:300px; width: 100%; padding: 7px; border:1px solid rgb(204, 204, 204); border-radius: 0px; box-shadow: 0px 1px 1px rgba(0, 0, 0, 0.075) inset; transition: border-color 0.15s ease-in-out 0s, box-shadow 0.15s ease-in-out 0s;", placeholder: "Compose your new post ..."%>
      </div>
      <script type="text/javascript">
        $(document).ready(function(){
          $('.wysihtml5').each(function(i, elem) {
            $(elem).wysihtml5();
          });
        });
      </script>
      <%= f.submit "Post", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<hr />

app/views/layouts/_profile_header.html.erb
<div class="media">
  <a class="pull-left" href="<%= user_path(@user) %>">
    <%= gravatar_for @user %>
  </a>
  <div class="media-body">
    <h4 class="media-heading"><%= "#{@user.first_name} #{@user.surname}" %></h4>
    <p><strong>Email: </strong> <%= @user.email %></p>
    <p><%= @user.about.nil? ? @user.about : "No about info" %></p>
    <%= render "shared/stats" %>
    <div>
      <%= render "follow_form" if signed_in? %>
    </div>
  </div>
</div>

app/views/layouts/_sign_in_form.html.erb
<%= form_for(:session, :url => sessions_path, :html => {:class => "form-signin"}) do |f| %>
  <h2 class="form-signin-heading">Sign in</h2>
  <% if flash[:error] %>
    <%= render "shared/session_sign_in_error_message" %>
  <% end %>
  <%= f.email_field :email, class: "form-control", placeholder: "email" %>
  <%= f.password_field :password, class: "form-control", placeholder: "password" %>
  <%= f.submit "Sign in", class: "btn btn-lg btn-primary btn-block" %>
  <h5>Don't have an account? <%= link_to "Sign up", signup_path %></h5>
<% end %>

app/views/layouts/_sign_up_form.html.erb
<%= form_for @user, html: { class: "form-signin" } do |t| %>
  <h2 class="form-signin-heading">Sign up</h2>
  <%= render "shared/user_create_error_message" %>
  <% if @user.errors.include?(:first_name) %>
    <span class="label label-danger"><%= @user.errors.full_messages_for(:first_name) %></span>
  <% end %>
  <%= t.text_field :first_name, class: "form-control", placeholder: "first name" %>
  <% if @user.errors.include?(:surname) %>
    <span class="label label-danger"><%= @user.errors.full_messages_for(:surname) %></span>
  <% end %>
  <%= t.text_field :surname, class: "form-control", placeholder: "last name" %>
  <% if @user.errors.include?(:email) %>
    <span class="label label-danger"><%= @user.errors.full_messages_for(:email) %></span>
  <% end %>
  <%= t.email_field :email, class: "form-control", placeholder: "email" %>
  <% if @user.errors.include?(:about) %>
    <span class="label label-danger"><%= @user.errors.full_messages_for(:about) %></span>
  <% end %>
  <%= t.text_area :about, class: "form-control", style: "display: block; height:300px; width: 100%; padding: 7px; border:1px solid rgb(204, 204, 204); border-radius: 0px; box-shadow: 0px 1px 1px rgba(0, 0, 0, 0.075) inset; transition: border-color 0.15s ease-in-out 0s, box-shadow 0.15s ease-in-out 0s;", placeholder: "something about you" %>
  <% if @user.errors.include?(:password) %>
    <span class="label label-danger"><%= @user.errors.full_messages_for(:password) %></span>
  <% end %>
  <%= t.password_field :password, class: "form-control", placeholder: "password" %>
  <% if @user.errors.include?(:password_confirmation) %>
    <span class="label label-danger"><%= @user.errors.full_messages_for(:password_confirmation) %></span>
  <% end %>
  <%= t.password_field :password_confirmation, class: "form-control", placeholder: "confirm password" %>
  <%= t.submit "Sign up", class: "btn btn-lg btn-primary btn-block" %>
  <h5>Already have an account? <%= link_to "Sign in", signin_path %></h5>
<% end %>

app/views/layouts/_ui_dependencies.html.erb
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= full_title(yield(:title)) %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Writup" %>">
    <%= render 'layouts/ui_dependencies' %>
  </head>
  <body>
    <header>
      <% if signed_in? %>
        <%= render 'layouts/navigation' %>
      <% else %>
        <%= render 'layouts/navigation_not_signed_in' %>  
      <% end %>
    </header>
    <main role="main">
       <%= yield %>
    </main>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>